# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: product-service

frameworkVersion: '2'

variablesResolutionMode: 20210326

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  profile: ${env:AWS_PROFILE}
  stage: dev
  environment:
    DB_USER: ${env:DB_USER}
    DB_SERVER: ${env:DB_SERVER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT}
    AWS_UPLOAD_BUCKET: ${env:AWS_UPLOAD_BUCKET}
    AWS_UPLOAD_BUCKET_CATALOG: ${env:AWS_UPLOAD_BUCKET_CATALOG}

  iamRoleStatements:
    - Effect: 'Allow'
      Action: 's3:ListBucket'
      Resource:
        - Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - ${env:AWS_UPLOAD_BUCKET}
plugins:
  - serverless-offline
  - serverless-webpack

package:
  individually: true

functions:
  getProductsList:
    handler: product-service/getProductsList.handler
    events:
      - http:
          path: products
          method: GET
          cors:
            origin: '*'
  getProductsById:
    handler: product-service/getProductsById.handler
    events:
      - http:
          path: products/{productId}
          method: GET
          cors:
            origin: '*'
  createProduct:
    handler: product-service/createProduct.handler
    events:
      - http:
          path: products
          method: POST
          cors:
            origin: '*'
  importProductsFile:
    handler: import-service/importProductsFile.handler
    events:
      - http:
          path: import
          method: GET
          cors:
            origin: '*'
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: import-service/importFileParser.handler
    events:
      - s3:
          bucket: ${env:AWS_UPLOAD_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${env:AWS_UPLOAD_BUCKET_CATALOG}/
            - suffix: .csv
          existing: true

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'npm'
    excludeFiles: '__tests__/**/*.test.ts'
