openapi: 3.0.0
info:
  title: RS Guitar Store API
  description: Guitar Store
  version: 1.0.0
servers:
  - url: https://a950j0y0ld.execute-api.eu-west-1.amazonaws.com/dev
    description: Dev server
components:
  schemas:
    Product:
      properties:
        id:
          type: string
        description:
          type: string
        price:
          type: integer
        title:
          type: string
        image:
          type: string
paths:
  /products:
    get:
      summary: Returns a list of products.
      responses:
        '200':
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{productId}:
    get:
      summary: Returns a product
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: UUID of the product to get
      responses:
        '200':
          description: Product object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
